config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session
  resources :comments
  resources :goals

  resources :user_comments
  resources :goal_comments

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  user_id          :integer          not null
#  body             :text             not null
#  commentable_type :string           not null
#  commentable_id   :integer          not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Comment < ActiveRecord::Base

  validates :commentable_id, :commentable_type, :user_id, :body, presence: true

  belongs_to :commentable, polymorphic: true
  belongs_to :author, foreign_key: :user_id, class_name: "User"

end

app/controllers/comments_controller.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  user_id          :integer          not null
#  body             :text             not null
#  commentable_type :string           not null
#  commentable_id   :integer          not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class CommentsController < ApplicationController

  before_action :redirect_unless_logged_in

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to url_for(@comment.commentable)
    elsif @comment.commentable_type && @comment.commentable_id
      flash[:errors] = @comment.errors.full_messages
      redirect_to url_for(@comment.commentable)
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to user_url(current_user)
    end
  end

  def destroy
    @comment = Comment.find_by_id(params[:id])
    @comment.destroy
    redirect_to url_for(@comment.commentable)
  end

  private

  def comment_params
    params.require(:comment).permit(:commentable_id, :commentable_type, :body)
  end


end

app/helpers/comments_helper.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  user_id          :integer          not null
#  body             :text             not null
#  commentable_type :string           not null
#  commentable_id   :integer          not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

module CommentsHelper
end

app/views/comments/_form.html.erb
<h4>Make Comment</h4>

<form action="<%= comments_url %>" method="POST">
  <%= auth_token %>
  <label for="body">Body</label>
  <input type="text" name="comment[body]" id="body">

  <input type="hidden" name="comment[commentable_id]" value="<%= subject.id %>">
  <input type="hidden" name="comment[commentable_type]" value="<%= subject.class %>">

  <input type="submit" value="Submit Comment">
</form>

app/views/comments/_one_comment.html.erb
<%= comment.author.username %> <br>
<%= comment.body %> <br>
<%= button_to "Remove Comment", comment_url(comment), method: :delete if current_user.id == comment.user_id %>
<br><br>