config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session
  resources :comments
  resources :goals

  resources :user_comments
  resources :goal_comments

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base

  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  attr_reader :password

  has_many :goals, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def generate_session_token
    SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save
    self.session_token
  end

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return nil if user.nil?
    return user if user.is_password?(password)
    nil
  end



end

app/controllers/users_controller.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/users_helper.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

module UsersHelper
end

app/views/users/_form.html.erb
<% action = form_type == "Sign Up" ? users_url : session_url %>
<% button = form_type == "Sign Up" ? "Sign Up" : "Sign In" %>
<form action="<%= action %>" method="POST">
  <%= auth_token %>
  <label for="username">Username</label>
  <input type="text" name="user[username]" value="<%= user.username %>" id="username">

  <label for="password">Password</label>
  <input type="password" name="user[password]" value="<%= user.password %>" id="password">

  <input type="submit" value="<%= button %>">

</form>

app/views/users/_header.html.erb
<% if current_user %>
  <%= current_user.username %>
  <%= button_to "Sign Out", session_url, method: :delete %>
<% end %>

app/views/users/new.html.erb
<h2>Sign Up</h2>
<%= render 'form', user: @user, form_type: "Sign Up" %>

app/views/users/show.html.erb
<h2><%= @user.username %></h2>

<%= link_to "Make Goal", new_goal_url if current_user %>

<h4> Goals: </h4>
<% @user.goals.each do |goal| %>
  <% next if goal.pprivate && @user.id != current_user.id %>
  <%= link_to goal.description, goal_url(goal) %><br>
  <%= "private" if goal.pprivate %><br>
  <%= render 'goals/done_button', goal: goal %><br>
<% end %>

<% @user.comments.each do |comment| %>
  <%= render 'comments/one_comment', comment: comment %>
<% end %>

<%= render 'comments/form', subject: @user %>