config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session
  resources :comments
  resources :goals

  resources :user_comments
  resources :goal_comments

end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id          :integer          not null, primary key
#  description :text             not null
#  user_id     :integer          not null
#  completed   :boolean          default(FALSE), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  pprivate    :boolean          default(FALSE), not null
#

class Goal < ActiveRecord::Base
  validates :description, :user_id, presence: true
  validates :pprivate, :completed, inclusion: {in: [true, false]}

  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :user


  def complete!
    self.completed = true
    self.save
  end

end

app/controllers/goals_controller.rb
# == Schema Information
#
# Table name: goals
#
#  id          :integer          not null, primary key
#  description :text             not null
#  user_id     :integer          not null
#  completed   :boolean          default(FALSE), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  pprivate    :boolean          default(FALSE), not null
#

class GoalsController < ApplicationController

  before_action :redirect_unless_logged_in
  before_action :require_correct_user!, only: [:edit, :update, :destroy]

  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    @goal.completed = false
    if @goal.save
      redirect_to user_url(current_user)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def update
    @goal = find_goal
    if @goal.update(goal_params)
      redirect_to user_url(current_user)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def edit
    @goal = find_goal
  end

  def destroy
    @goal = find_goal
    @goal.destroy
    redirect_to user_url(current_user)
  end

  def show
    @goal = find_goal
  end

  private

  def goal_params
    params.require(:goal).permit(:description, :completed, :pprivate)
  end

  def require_correct_user!
    redirect_to new_session_url unless find_goal.user_id == current_user.id
  end

  def find_goal
    Goal.find_by_id(params[:id])
  end

end

app/helpers/goals_helper.rb
# == Schema Information
#
# Table name: goals
#
#  id          :integer          not null, primary key
#  description :text             not null
#  user_id     :integer          not null
#  completed   :boolean          default(FALSE), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  pprivate    :boolean          default(FALSE), not null
#

module GoalsHelper
end

app/views/goals/_done_button.html.erb
<% if goal.completed %>
  <%= "Completed" %>
<% elsif goal.user_id == current_user.id %>

  <form action="<%= goal_url(goal) %>" method="POST">
    <input type="hidden" name="_method" value="PATCH">
    <%= auth_token %>
    <input type="hidden" name="goal[completed]" value="true">
    <input type="submit" value="Done">
  </form>

  <%= button_to "Give Up", goal_url(goal), method: :delete %>

<% else %>

  <%= "Goal in progress" %>

<% end %>

app/views/goals/_form.html.erb
<% action = goal.persisted? ? goal_url(goal) : goals_url %>
<% method = goal.persisted? ? "PATCH" : "POST" %>
<% button = goal.persisted? ? "Update Goal" : "Make Goal" %>
<% checked = goal.persisted? ? goal.pprivate : false %>

<form action="<%= action %>" method="POST">

  <%= auth_token %>

  <input type="HIDDEN" name="_method" value="<%= method %>">

  <label for="description">Description: </label>
  <input type="text" name="goal[description]" id="description"
    value="<%= goal.description %>">
  <br>
  <input type="radio" name="goal[pprivate]" value="false" id="Public" <%= "CHECKED".html_safe unless checked %> >Public<br>
  <input type="radio" name="goal[pprivate]" value="true" id="Private" <%= "CHECKED".html_safe if checked %>     >Private<br>

  <input type="submit" value="<%= button %>">
</form>

app/views/goals/edit.html.erb
<h2> Edit Goal </h2>

<%= render 'form', goal: @goal %>

app/views/goals/new.html.erb
<h2> Make Goal </h2>

<%= render 'form', goal: @goal %>

app/views/goals/show.html.erb
<h3> <%= @goal.description %> </h3>
by <%= link_to @goal.user.username, user_url(@goal.user) %><br>

<br>
Comments:<br>
<% @goal.comments.each do |comment| %>
  <%= render 'comments/one_comment', comment: comment %>
<% end %>
<br>
<%= render 'comments/form', subject: @goal %>